# Generated by Django 5.1.2 on 2024-10-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlmsgivingRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temple_name", models.CharField(max_length=255)),
                ("starting_point_name", models.CharField(max_length=255)),
                ("starting_point_lat", models.FloatField()),
                ("starting_point_lng", models.FloatField()),
                ("ending_point_name", models.CharField(max_length=255)),
                ("ending_point_lat", models.FloatField()),
                ("ending_point_lng", models.FloatField()),
                ("average_time", models.CharField(max_length=8)),
                ("distance", models.FloatField()),
                ("number_of_monks", models.IntegerField()),
                ("route_description", models.TextField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
