# Generated by Django 5.1.3 on 2024-12-11 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0003_prayerpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerpost',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,null=True),
        ),
        migrations.AddField(
            model_name='prayerpost',
            name='post_type',
            field=models.CharField(choices=[('news', 'News'), ('announcement', 'Announcement'), ('event', 'Event')], default='news', max_length=20),
        ),
    ]
