# Generated by Django 5.1.3 on 2024-12-11 08:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0004_prayerpost_author_prayerpost_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('img', models.ImageField(blank=True, null=True, upload_to='prayers_images/')),
                ('url', models.URLField(blank=True, null=True)),
                ('post_type', models.CharField(choices=[('news', 'News'), ('announcement', 'Announcement'), ('event', 'Event')], default='news', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PrayerPost',
        ),
    ]
