# Generated by Django 5.1.3 on 2024-12-11 13:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0005_newspost_delete_prayerpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayersPost',
            fields=[
                ('prayers_id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
