# Generated by Django 5.1.3 on 2024-12-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0008_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
