# Generated by Django 5.1.3 on 2025-01-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0011_chatroom_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='last_message',
            new_name='description',
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='message',
            name='attachment',
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='last_message_time',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user',
        ),
    ]
