# Generated by Django 5.1.3 on 2025-01-29 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0012_rename_last_message_chatroom_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('stop_time', models.IntegerField(default=0)),
                ('checkpoint_type', models.CharField(choices=[('home', 'บ้าน'), ('market', 'ตลาด'), ('community', 'ศูนย์ชุมชน'), ('rest', 'จุดพัก'), ('other', 'อื่นๆ')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('checkpoints', models.ManyToManyField(related_name='routes', to='monklingo.checkpoint')),
                ('monk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AlmsgivingRoute',
        ),
    ]
