# Generated by Django 5.1.3 on 2025-01-30 08:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0013_checkpoint_route_delete_almsgivingroute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpoint',
            name='checkpoint_type',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='name',
        ),
        migrations.RemoveField(
            model_name='checkpoint',
            name='stop_time',
        ),
        migrations.RemoveField(
            model_name='route',
            name='checkpoints',
        ),
        migrations.RemoveField(
            model_name='route',
            name='monk',
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='order',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='route',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='monklingo.route'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='travel_time',
            field=models.DurationField(default=None),
        ),
        migrations.AddField(
            model_name='route',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='lat',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='lon',
            field=models.FloatField(default=None),
        ),
    ]
