# Generated by Django 5.1.3 on 2025-01-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0014_remove_checkpoint_checkpoint_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
