# Generated by Django 5.1.3 on 2025-01-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0015_alter_checkpoint_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='order',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
