# Generated by Django 5.1.3 on 2025-01-30 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0016_alter_checkpoint_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='monklingo.route'),
        ),
    ]
