# Generated by Django 5.1.3 on 2025-01-30 09:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0017_alter_checkpoint_order_alter_checkpoint_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='order',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='route',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='monklingo.route'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='travel_time',
            field=models.DurationField(default=datetime.timedelta(seconds=600)),
        ),
    ]
