# Generated by Django 5.1.3 on 2025-01-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0018_alter_checkpoint_order_alter_checkpoint_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
