# Generated by Django 5.1.3 on 2025-01-30 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0019_alter_checkpoint_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='route',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='monklingo.route'),
        ),
    ]
