# Generated by Django 5.1.3 on 2025-01-30 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0020_alter_checkpoint_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='name',
            field=models.CharField(default='Checkpoint', max_length=255),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='order',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='travel_time',
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
        ),
    ]
