# Generated by Django 5.1.3 on 2025-03-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0022_temple_remove_route_duration_route_temple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
    ]
