# Generated by Django 5.1.3 on 2025-03-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0023_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='uploaded_at',
            field=models.DateTimeField(),
        ),
    ]
