# Generated by Django 5.1.3 on 2025-03-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0024_alter_userimage_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('event_type', models.CharField(choices=[('buddhist_day', 'วันพระ'), ('special_event', 'กิจนิมนต์'), ('weather', 'สภาพอากาศ'), ('other', 'เหตุการณ์อื่นๆ')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('is_canceled', models.BooleanField(default=False)),
            ],
        ),
    ]
