# Generated by Django 5.1.3 on 2025-03-07 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0025_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='temple',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='monklingo.temple'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
    ]
