# Generated by Django 5.1.3 on 2025-03-10 14:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0026_event_temple_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='temple',
            name='manager',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='temples', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('temple', 'date')},
        ),
    ]
