# Generated by Django 5.1.3 on 2025-03-10 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0028_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='created_by',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
