# Generated by Django 5.1.3 on 2025-03-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0029_route_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temple',
            old_name='manager',
            new_name='created_by',
        ),
    ]
