# Generated by Django 5.1.3 on 2025-03-10 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0030_rename_manager_temple_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL),
        ),
    ]
