# Generated by Django 5.1.3 on 2025-03-11 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monklingo', '0031_alter_route_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_temple',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='monklingo.temple'),
        ),
    ]
